export enum EntityNames {
  AssetType = 'AssetType',
  AssetTypeCategory = 'AssetTypeCategory',
  Area = 'Area',
  AddressType = 'AddressType',
  AuthorityOffice = 'AuthorityOffice',
  Branch = 'Branch',
  BusinessLine = 'BusinessLine',
  CallActionType = 'CallActionType',
  CallType = 'CallType',
  ClientType = 'ClientType',
  CommunicationFlowType = 'CommunicationFlowType',
  CommunicationType = 'CommunicationType',
  CompanyType = 'CompanyType',
  Country = 'Country',
  Currency = 'Currency',
  DocType = 'DocType',
  FeeCalculationType = 'FeeCalculationType',
  FeeType = 'FeeType',
  Governorate = 'Governorate',
}
