import { Component } from '@angular/core';
import { Calculation } from '../../../../../shared/interfaces/calculations.interface';

@Component({
  selector: 'app-leasing-financial-form-compound',
  standalone: false,
  templateUrl: './leasing-financial-form-compound.component.html',
  styleUrl: './leasing-financial-form-compound.component.scss',
})
export class LeasingFinancialFormCompoundComponent {
  tableDataInside: Calculation[] = [];

  colsInside: any[] = [];
  ngOnInit() {
    this.colsInside = [
      { field: 'code', header: 'Code' },
      { field: 'paymentNumber', header: 'Payment Number' },
      { field: 'dueDate', header: 'Due Date' },
      { field: 'balanceBefore', header: 'Balance Before' },
      { field: 'balanceAfter', header: 'Balance After' },
      { field: 'insuranceOutcome', header: 'Insurance Outcome' },
      { field: 'principal', header: 'Principal' },
      { field: 'installment', header: 'Installment' },
      { field: 'interest', header: 'Interest' },
      { field: 'nameEN', header: 'Name EN' },
      { field: 'nameAR', header: 'Name AR' },
    ];
    this.tableDataInside = [
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
      {
        code: 1,
        paymentNumber: 1,
        dueDate: new Date('01/10/2025'),
        balanceBefore: 50000,
        balanceAfter: 70000,
        insuranceOutcome: 0,
        principal: 7948,
        installment: 18000,
        interest: 7,
        nameAR: 'name ar',
        nameEN: 'name en',
      },
    ];
  }
}
