// src/app/pdf-export/pdf-export.component.ts
import { Component } from '@angular/core';
import * as pdfMake from 'pdfmake/build/pdfmake';
import { TDocumentDefinitions } from 'pdfmake/interfaces';
import { pdfMakeVfs } from '../pdfmake-vfs'; // the file generated by your script

@Component({
  selector: 'app-pdf-export',
  templateUrl: './pdf-export.component.html',
})
export class PdfExportComponent {
  // Example data — replace with your own table data
  tableBody = [
    ['مفتاح', 'الحقل 1', 'الحقل 2'],
    ['قيمة أ', 'بيانات أ1', 'بيانات أ2'],
    ['قيمة ب', 'بيانات ب1', 'بيانات ب2'],
  ];

  generatePdf() {
    const docDefinition: TDocumentDefinitions = {
      defaultStyle: { font: 'Amiri', alignment: 'right' },
      content: [
        { text: 'تقرير مثال', style: 'header' },
        {
          table: {
            headerRows: 1,
            widths: ['auto', '*', '*'],
            body: [
              this.tableBody[0].map((h) => ({ text: h, bold: true })),
              ...this.tableBody.slice(1),
            ],
          },
        },
      ],
      styles: {
        header: { fontSize: 18, bold: true, margin: [0, 0, 0, 10] },
      },
      pageSize: 'A4',
      pageMargins: [40, 60, 40, 60],
    };

    pdfMake.createPdf(docDefinition).download('report.pdf');
  }
}
